server:
  port: 4050

spring:
  rabbitmq:
    host: 47.98.104.86
    port: 5672
    username: root
    password: 0814mq0920

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023