server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.99.88.70:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    
zipkin:
  collector:
    rabbitmq:
      addresses: 47.98.104.86:5672
      username: root
      password: 0814mq0920
      queue: zipkin
  storage:
    type: mysql