server:
  port: 4050

spring:
  rabbitmq:
    host: 192.169.204.128
    port: 5672
    username: root
    password: root

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023